### show all users
GET http://localhost:1234/api/users/

### create a new user
POST http://localhost:1234/api/users/
Content-Type: application/json

{
    "nickname": "7.Ellie",
    "age": 22,
    "city": "Santa Cruz de Tenerife"
}

### modify a user
PATCH http://localhost:1234/api/users/67363f1487490ca7c99e67d5
Content-Type: application/json

{
    "city": "Turin"
}

### delete a user
DELETE http://localhost:1234/api/users/67363f1487490ca7c99e67d5

### show all posts
GET http://localhost:1234/api/posts/

### show a post by id
GET http://localhost:1234/api/posts/67363f1487490ca7c99e67d5

### create a new post that will has your id in json (you have to login to make a post)
POST http://localhost:1234/api/posts/
Content-Type: application/json

{
    "title": "prova con timestamps true",
    "content": "prova con timestamps true",
    "user": "67363f1487490ca7c99e67d5"
}

### modify a post - u only can change if u are the owner
PATCH http://localhost:1234/api/posts/67377acc81facdf55254407f
Content-Type: application/json

{
    "title": "prova con timestampstrue e modificato",
    "user": "67363f1487490ca7c99e67d5"
}

### delete a post - u only can delete if u are the owner
DELETE http://localhost:1234/api/posts/67377acc81facdf55254407f


### show all interactions
GET http://localhost:1234/api/interactions/

### show a interaction by id
GET http://localhost:1234/api/interactions/673792cc7a2ed0ae59057b58

### create a new interaction    
POST http://localhost:1234/api/interactions/
Content-Type: application/json

{
    "type": "comment",
    "post": "67377acc81facdf55254407f",
    "user": "67363f1487490ca7c99e67d5",
    "content": "commento 5"
}

### modify a interaction - u only can change if u are the owner
PATCH http://localhost:1234/api/interactions/673791361edbfdb6d4644519
Content-Type: application/json

{
    "user" : "673721fcbc8b496d6c78b30b",
    "type": "like"
}

### delete a interaction - u only can delete if u are the owner
DELETE http://localhost:1234/api/interactions/67379282971ffe8ee85417a9
