### show all users
GET http://localhost:1234/api/users/

### create a new user
POST http://localhost:1234/api/users/
Content-Type: application/json

{
    "nickname": "simonLimon",
    "age": 20,
    "city": "Milano"
}

### modify a user
PATCH http://localhost:1234/api/users/673b710d1043f700a3b48cbc
Content-Type: application/json

{
    "age": 21
}

### delete a user
DELETE http://localhost:1234/api/users/67363f1487490ca7c99e67d5

### show all posts
GET http://localhost:1234/api/posts/

### show post by filtered date
GET http://localhost:1234/api/posts/bydate/2024-11-18


### show a post by id
GET http://localhost:1234/api/posts/67372c3f88c1e0731cb36151

### create a new post that will has your id in json (you have to login to make a post)
POST http://localhost:1234/api/posts/
Content-Type: application/json

{
    "title": "buongiorno da Matteo",
    "content": "ciaooo",
    "user": "673b41b53348a423e549abfb"
}

### modify a post - u only can change if u are the owner
PATCH http://localhost:1234/api/posts/67377acc81facdf55254407f
Content-Type: application/json

{
    "title": "prova con timestampstrue e modificato",
    "user": "67363f1487490ca7c99e67d5"
}

### delete a post - u only can delete if u are the owner
DELETE http://localhost:1234/api/posts/67377acc81facdf55254407f
Content-Type: application/json

{
    "user": "67363f1487490ca7c99e67d5"
}


### show all interactions
GET http://localhost:1234/api/interactions

### search interaction by city and date with query params
GET http://localhost:1234/api/interactions/search?userCity=Torino

### show a interaction by id
GET http://localhost:1234/api/interactions/673792cc7a2ed0ae59057b58

### create a new interaction    
POST http://localhost:1234/api/interactions/
Content-Type: application/json

{
    "type": "comment",
    "post": "673b275137bf3ed74283b12f",
    "user": "673b41b53348a423e549abfb",
    "content": "urgente"
}

### modify a interaction - u only can change if u are the owner
PATCH http://localhost:1234/api/interactions/673791361edbfdb6d4644519
Content-Type: application/json

{
    "user" : "673721fcbc8b496d6c78b30b",
    "type": "like"
}

### delete a interaction - u only can delete if u are the owner
DELETE http://localhost:1234/api/interactions/67379282971ffe8ee85417a9
Content-Type: application/json

{
    "user" : "67363f1487490ca7c99e67d5"
}
